name: .NET

on:
  push:
    branches:
      - main
      - staging
      - development

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.x' # Update to the desired version

    - name: Build API
      run: dotnet build ./API/API.csproj --configuration Release

    - name: Test UserTests
      run: dotnet test ./UserTests/UserTests.csproj --configuration Release
