name: .NET

on:
  push:
    branches:
      - main
      - staging
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x' # Update to the desired version

      - name: Build API
        run: dotnet build ./API/API.csproj --configuration Release

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x' # Update to the desired version

      - name: Test 
        run: dotnet test ./Test/Test.csproj --configuration Release

  docker-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.ORG_DOCKERHUB_USERNAME }} -p ${{ secrets.ORG_DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build -t ${{ secrets.ORG_DOCKERHUB_USERNAME }}/UserService:latest .

      - name: Push the Docker image to Docker Hub
        run: docker push ${{ secrets.ORG_DOCKERHUB_USERNAME }}/UserService:latest
